# Generated by Django 5.2.2 on 2026-02-03 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_company_industry_company_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='url',
            field=models.URLField(max_length=100, null=True),
        ),
    ]
